#ifndef QTBARCODEREADER_GLOBAL_H
#define QTBARCODEREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTBARCODEREADER_LIBRARY)
#  define QTBARCODEREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTBARCODEREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTBARCODEREADER_GLOBAL_H
