#ifndef QTBARCODEREADER_GLOBAL_H
#define QTBARCODEREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTBARCODEREADER_LIBRARY)
#  define QTBARCODEREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTBARCODEREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

enum QTBARCODEREADERSHARED_EXPORT BARCODESTATUS { BARCODEREADED= 1,NOREAD= 2 };

#endif // QTBARCODEREADER_GLOBAL_H
